"use client";
import {useEffect,useState} from 'react';
import {isLiveListing} from '@/lib/eligibility';
import {ArrowUpRight,Search,Radar,ShieldCheck,Clock3,Camera} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import models from '@/data/models.json';
import initialFeed from '@/data/feed.json';
import history from '@/data/history.json';
const money=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
const date=(s:string)=>new Date(s).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/London'});
export default function CarBrowser({initialNow}:{initialNow:number}){
 const [feed,setFeed]=useState(initialFeed),[q,setQ]=useState(''),[now,setNow]=useState(initialNow),[tab,setTab]=useState('latest'),[error,setError]=useState(false);
 useEffect(()=>{let active=true;const refresh=async()=>{if(active)setNow(Date.now());try{const r=await fetch('/api/feed',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json() as typeof initialFeed;if(!Array.isArray(d.listings)||!Array.isArray(d.watches)||!Array.isArray(d.runs))throw Error();if(active){setFeed(d);setError(false);setNow(Date.now())}}catch{if(active)setError(true)}};refresh();const id=setInterval(refresh,60000);return()=>{active=false;clearInterval(id)}},[]);
 const live=feed.listings.filter(l=>isLiveListing(l,now)).sort((a,b)=>Number(a.discoveryType==='history')-Number(b.discoveryType==='history')||Date.parse(b.firstSeen)-Date.parse(a.firstSeen));
 const matches=live.filter(l=>(l.title+' '+l.location+' '+l.seller).toLowerCase().includes(q.toLowerCase()));
 const filteredHistory=history.filter(h=>(h.label+' '+h.source).toLowerCase().includes(q.toLowerCase()));
 const filteredModels=models.filter(m=>(m.make+' '+m.name+' '+m.group).toLowerCase().includes(q.toLowerCase()));
 return <main><header className="masthead"><a href="/" className="brand"><span className="brandmark">GP<span>.</span></span><span>GAVIN’S PICKS<span className="brand-light"> / CARS</span></span></a><span className="private-label">THE UK MOTOR WATCH <span className="status-dot"/></span></header>
 <div className="workspace"><div className="intro"><div><p className="eyebrow">THE UK SEARCH / 1995—2010</p><h1>The ones worth finding<span>.</span></h1><p className="sub">Manuals. Limited runs. Modern classics.</p></div><div className="budget"><span>PURCHASE RANGE</span><strong>£10k <span>—</span> £100k</strong><small>Explicit asking prices only</small></div></div>
 <div className="metrics"><div><strong>{live.length.toString().padStart(2,'0')}</strong><span>Verified live finds</span></div><div><strong>{models.length}</strong><span>Watchlist targets</span></div><div><ShieldCheck size={23}/><span>Photos & status checked</span></div><div><Clock3 size={23}/><span>Updated {date(feed.updatedAt)}</span></div></div>
 {error&&<p className="notice" role="status">Could not refresh the feed. Showing the last loaded results; older checks expire automatically.</p>}
 <Tabs value={tab} onValueChange={v=>{setTab(String(v));setQ('')}}><div className="toolbar"><TabsList variant="line" className="tablist"><TabsTrigger value="latest">Latest finds <span className="count">{live.length}</span></TabsTrigger><TabsTrigger value="watchlist">Full watchlist</TabsTrigger><TabsTrigger value="history">Recovered finds <span className="count">{history.length}</span></TabsTrigger><TabsTrigger value="schedule">Search activity</TabsTrigger></TabsList>{tab!=='schedule'&&<div className="search"><Search size={17}/><Input aria-label="Search cars" placeholder={tab==='latest'?'Search car, seller or location':tab==='history'?'Search recovered advert or source':'Search make or model'} value={q} onChange={e=>setQ(e.target.value)}/></div>}</div>
 <TabsContent value="latest"><div className="section-line"><span>NEW DISCOVERIES, THEN RECOVERED FINDS</span><span>Checks expire after 24 hours</span></div><div className="car-grid">{matches.map((l,i)=><article className="car" key={l.id}><a className="car-image" href={l.url} target="_blank" rel="noreferrer"><img src={l.image} alt={l.title+' — seller photograph'} loading={i<3?'eager':'lazy'} referrerPolicy="no-referrer"/><span className="verified"><Camera size={14}/> PHOTO CHECKED</span></a><div className="car-body"><div className="car-top"><span>{l.year} / {l.gearbox}</span><span className="available">Available</span></div><h2><a href={l.url} target="_blank" rel="noreferrer">{l.title}</a></h2><div className="price-row"><strong>{money(l.price)}</strong></div><p className="spec">{l.mileage===null?'Mileage not stated':l.mileage.toLocaleString('en-GB')+' miles'} · {l.location}</p><p className="seller">{l.seller}</p><p className="notes">{l.notes}</p><details><summary>View verification</summary><p>{l.evidence}</p><p>{l.photoEvidence}</p><p>{l.discoveryType==='history'?'Recovered from watch history · imported':'First found'} {date(l.firstSeen)} · checked {date(l.checkedAt)}</p></details><a className="listing-link" href={l.url} target="_blank" rel="noreferrer">Open original advert <ArrowUpRight size={18}/></a></div></article>)}</div>{!matches.length&&<Empty className="empty"><EmptyHeader><Radar size={38}/><EmptyTitle className="empty-title">{q?'No cars match that search':'Nothing unverified makes the cut.'}</EmptyTitle><EmptyDescription>{q?'Try another make, model or location.':'New finds appear after the price, specification, availability and seller photographs are checked. POA, sold, reserved and uncertain adverts stay out.'}</EmptyDescription></EmptyHeader></Empty>}<p className="footnote">Availability checked online at the time shown. Confirm with the seller before travelling. A newly discovered advert is not necessarily newly listed by its seller.</p></TabsContent>
 <TabsContent value="watchlist"><div className="section-line"><span>{filteredModels.length} SEARCH TARGETS</span><span>Guide prices are not live adverts</span></div><Table><TableHeader><TableRow><TableHead>MAKE / MODEL</TableHead><TableHead>YEARS</TableHead><TableHead>SHOPPING GUIDE</TableHead><TableHead>WHY IT IS WATCHED</TableHead></TableRow></TableHeader><TableBody>{filteredModels.map(m=><TableRow key={m.id}><TableCell><span className="table-make">{m.make}</span><strong>{m.name}</strong></TableCell><TableCell>{m.from}–{m.to}</TableCell><TableCell>{money(m.guideMin)}–{money(m.guideMax)}</TableCell><TableCell>{m.note}</TableCell></TableRow>)}</TableBody></Table><p className="footnote">The full original shortlist plus recovered car watches. Every live find must meet £10k–£100k and 1995–2010. Factory manual unless the model explicitly allows a rare paddle-shift special or documented Aston Works conversion. Shopping guides are indicative, not verified current prices.</p></TabsContent>
 <TabsContent value="history"><div className="section-line"><span>{filteredHistory.length} RECOVERED ADVERT LINKS</span><span>Historical leads · not a live-stock list</span></div><p className="footnote">Recovered from your car-watch history for this backfill. Exact alert times were unavailable for some scheduled reports, so these are not labelled as newly listed. Multiple adverts may refer to the same car. Only independently rechecked cars enter Latest finds.</p><Table><TableHeader><TableRow><TableHead>RECOVERED ADVERT</TableHead><TableHead>SOURCE</TableHead><TableHead>CURRENT CHECK</TableHead></TableRow></TableHeader><TableBody>{filteredHistory.map(h=>{const current=live.find(l=>l.url===h.url);return <TableRow key={h.id}><TableCell><a href={h.url} target="_blank" rel="noreferrer">{h.label} ↗</a></TableCell><TableCell>{h.source}</TableCell><TableCell><strong>{current?'In current finds':h.status==='excluded'?'Excluded':'Needs current check'}</strong><p>{h.note}</p></TableCell></TableRow>})}</TableBody></Table>{!filteredHistory.length&&<p className="notice">No recovered adverts match that search.</p>}</TabsContent>
 <TabsContent value="schedule"><div className="section-line"><span>YOUR SEARCHES</span><span>Europe / London</span></div><div className="watch-grid">{feed.watches.map(w=><article className="watch" key={w.id}><Radar size={20}/><h2>{w.name}</h2><p>{w.cadence}</p><span>{w.status}</span></article>)}</div><h2 className="activity-title">Latest checks</h2>{feed.runs.slice().reverse().slice(0,20).map(r=><div className="run" key={r.at}><time>{date(r.at)}</time><p>{r.summary}</p><span>{r.added} added · {r.removed} removed</span></div>)}</TabsContent></Tabs>
 <footer><span>GAVIN’S PICKS / CARS</span><span>Good cars. Clear prices. Current evidence.</span></footer></div></main>
}
